### ISSUE TITLE
Error code 200?

### ISSUE THREAD

**Issue by rosano** [0dataapp/hello#1]
I tried updating and deleting in the latest Firefox private mode and it seems like there is an alert because the code is 200:
<img width="360" alt="Screen Shot 2021-10-15 at 10 42 04" src="https://user-images.githubusercontent.com/1680612/137506801-904aa4bb-8b9e-4482-8de7-95a5e2f5c718.png">

<img width="360" alt="Screen Shot 2021-10-15 at 10 43 54" src="https://user-images.githubusercontent.com/1680612/137506803-545319ce-02e0-46fc-b253-91a2fe47e1e4.png">

I was going to just change [solid.js#L158](https://github.com/0dataapp/hello-world-solid/blob/ca477f8f902971f71d3d96a072e9df891c10970f/solid.js#L158) and [solid.js#L165](https://github.com/0dataapp/hello-world-solid/blob/ca477f8f902971f71d3d96a072e9df891c10970f/solid.js#L165) but I don't know if they're supposed to check for `205`:

**Comment by NoelDeMartin** [comment]
Ok, I just changed it to check for `2XX` status codes. I actually do this in my apps already, but I wanted to keep it simpler here.

This is a good example of the challenges of developing Solid apps, so I'm glad we found it :). I was testing this with [CSS](https://github.com/solid/community-server) and it worked properly, but it seems like Inrupt's POD doesn't behave the same way. When this happens, the idea is that you should look at [the spec](https://solidproject.org/TR/protocol) to see if this is a bug on Inrupt's POD or it's working correctly. But I don't see any specific mention about what the response status codes should be. So I suppose it's ok to consider any `2XX` as a correct response.
