### ISSUE TITLE
Organize Solid examples

### ISSUE THREAD

**Issue by NoelDeMartin** [0dataapp/hello#10]
Follow-up to the discussion from #8

**Comment by rosano** [comment]
> I see no reason why I wouldn't add one for solid-client and soukai, probably LDFlex as well. So I'm not sure how to organize all that

All welcome. Maybe instead of having a huge line of Solid examples, you can make a seperate index: `[Solid](/solid) ([Other examples](/solid/all))` or `Solid: [Main](/solid), [Other examples](/solid/all)`
