### ISSUE TITLE
make solid repo really multi-app

### ISSUE THREAD

**Issue by bourgeoa** [0dataapp/hello#15]
Actually there is a reference solid app and and access to other solid versions.

- hello/solid
   - solid-file-client
   - common solid files and solid app files

I propose an other organisation renaming the solid reference app --> solid-rest-api
We could have :
- hello/solid
  - solid-rest-api
  - solid-file-client
  - .... any other
  - common files : 
    - index.html with a list of all solid versions
    - eventually a README.md
    - could eventually contain the login/logout functions see issue #3

**Comment by NoelDeMartin** [comment]
I like the idea of renaming the reference app to `solid-rest-api`, but I think extracting more common code for solid could complicate the repo too much. Although maybe it'll be necessary if we have more examples, but only with 2 I think I'd leave it as is (following the [rule of 3](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) :D).

We already have an html listing all the solid versions here: https://hello.0data.app/solid/all.html

**Comment by bourgeoa** [comment]
> We already have an html listing all the solid versions here: https://hello.0data.app/solid/all.html

Yes I was only thinking of renaming `all.html` to `index.html`

I have nothing against the rule of 3

**Comment by NoelDeMartin** [comment]
I see, I think I understand what you mean now, you mean to move the files that are currently in `solid/` into `solid/solid-rest-api` and leave in `solid/` only the things that are common to all examples?

Ok I think that's a good idea, I'll do it the next time I change something in the repo (or open a PR yourself if you want).

**Comment by bourgeoa** [comment]
That is exactly what I meant.
