### ISSUE TITLE
Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by bourgeoa** [0dataapp/hello#2]
![image](https://user-images.githubusercontent.com/2218470/142730787-e423fd84-35b8-4951-a57b-ee0ad6c6e3a0.png)
```
solid.js:236 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at getSolidDocumentUrl (solid.js:236)
    at performTaskUpdate (solid.js:98)
    at updateTask (main.js:56)
    at HTMLButtonElement.onclick (VM15:1)
```

**Comment by NoelDeMartin** [comment]
Thanks Alain :). It seems like this was another case of something that's different in [NSS](https://github.com/solid/node-solid-server) and [CSS](https://github.com/solid/community-server). In CSS, the `Location` header of new documents is absolute, whilst NSS was returning a relative url. But both of those are correct, so I fixed the code.

**Comment by bourgeoa** [comment]
I think you should open an issue.

I always thought NSS was wrong, but was unable to compare with other implementation.

This may have implication in other app or libraries like solid-file-client. I also remember having a discussion with @jeff-zucker on solid-rest when implementing POST.

**Comment by jeff-zucker** [comment]
@NoelDeMartin, can you point to documentation for " both of those are correct"?  I've tripped over this several times and it would be nice to know if there's a definitive answer.

**Comment by NoelDeMartin** [comment]
@jeff-zucker @bourgeoa Good point, before posting my response I looked at [the solid spec](https://github.com/solid/specification) and I didn't find a clear answer. But then, I searched for the description of the `Location` header, which is not something specific to Solid, and [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location) describes it as `A relative (to the request URL) or absolute URL`. I suppose if no exception is made in the Solid spec, the general behaviour should apply. I'm also not sure if MDN can be considered normative, but I trust that it is correct.

**Comment by bourgeoa** [comment]
@jeff-zucker @NoelDeMartin https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30 says that the location must be an absolute URI.

Should I understand that fetch return a location that is relative but http POST header location  MUST return an absolute URI (URL for Solid) ? In that case NSS is wrong.

**Comment by NoelDeMartin** [comment]
@bourgeoa that is very weird :/ does that mean that the MDN documentation is wrong? I guess we should create an issue in NSS or the Solid spec, because this is way beyond the scope of this hello world.

**Comment by bourgeoa** [comment]
I don't think it is wrong, they just don't speak of the same thing. when
fetching from an express server the returned location is related to the
express server and not to the outside world (URL). Http headers and fetch
headers are not identicals.

**Comment by jeff-zucker** [comment]
> @jeff-zucker @NoelDeMartin https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30 says that the location must be an absolute URI.

I do **not** see that substantiated in the section you provide.  14.30 says that "the Location is that of the new resource".  Where does it indicate whether it is an absolute or  relative reference to that resource?

**Comment by jeff-zucker** [comment]
P.S. specs aside, my preference is to return the full URL.  It doesn't cost much and provides a benefit to clients.

**Comment by bourgeoa** [comment]
@jeff-zucker see last line `The field value consists of a single absolute URI`

**Comment by jeff-zucker** [comment]
@bourgeoa - duh.  Next time I will, as my mother used to say, "look with my eyes open".

**Comment by csarven** [comment]
https://github.com/solid/node-solid-server/issues/1507#issuecomment-977009385

Make sure to refer to spec versions that's claimed to be implemented by software. MDN is only documentation (interpreted) of the actual specifications. So, refer to original specs... Solid stuff is mostly under W3C or IETF.
