### ISSUE TITLE
Code organisation for better first coder experience

### ISSUE THREAD

**Issue by bourgeoa** [0dataapp/hello#3]
A good idea could be to make an auth.js separating login/logout from the rest of the app

**Comment by NoelDeMartin** [comment]
Hm I don't know if that would be better, I like that we only have two JS files. And it's only two to separate Solid specifics from app code, it was a single file in the first version but we decided to separate them to make Hello Worlds in other protocols using the same template. Maybe we could reorder the contents of `solid.js` instead or separate auth from CRUD with comments? Or maybe more files is better?

Any thoughts @rosano?

**Comment by rosano** [comment]
This is the kind of optimization that should be considered after the other protocols are implemented (be it in other repositories, or in this one). The separation of Solid concerns from the rest of the app *is* instructive for first-timers. Let's see what emerges and decide later.
